version: '3.4'

services:
  mssql:
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD} 
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    volumes:
      - mssql:/var/opt/mssql
    restart: always 

  redis:
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: always

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "7070:80"
    volumes:
      - seq:/data
    restart: always

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    restart: always

  book.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=6060
      - MSSQL_CONNECTION_STRING=Server=mssql,1433;Database=BookDB;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true; 
      - REDIS_CONNECTION_STRING=redis:6379,password=${REDIS_PASSWORD}
      - AUTH_ISSUER=${AUTH_ISSUER}
      - WEB_AUDIENCE=${WEB_AUDIENCE}
      - JWT_SECURITY_KEY=${JWT_SECURITY_KEY}
      - IDENTITY_ENDPOINT=${IDENTITY_ENDPOINT}
      - SERVER_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - SERVER_SECRET_KEY=${MINIO_SECRET_KEY}
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - SERVER_ENDPOINT=minio
    ports:
      - "6060:6060"
      - "6061:6061"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: always

  monitoring.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Email__From=${EMAIL_FROM} 
      - Email__Host=${EMAIL_HOST}
      - Email__Port=${EMAIL_PORT}
      - Email__Username=${EMAIL_USERNAME}
      - Email__Password=${EMAIL_PASSWORD}
      - HealthChecksUI__HealthChecks__0__Name=Book api
      - HealthChecksUI__HealthChecks__0__Uri=http://book.api:6060/health
      - HealthChecksUI__Webhooks__0__Name=Telegram
      - HealthChecksUI__Webhooks__0__Uri=https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage?chat_id=${TELEGRAM_CHAT_ID}
      - HealthChecksUI__Webhooks__0__Payload=${TELEGRAM_PAYLOAD}
      - HealthChecksUI__Webhooks__0__RestoredPayload=${TELEGRAM_RESTORED_PAYLOAD}
      - HealthChecksUI__EvaluationTimeInSeconds=10
    ports:
      - "8081:8081"
      - "8080:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: always

volumes:
  frontend:
  minio:
  pgadmin:
  postgres:
  redis:
  seq:
  mssql:
  