version: '3.4'

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest

  redis:
    container_name: redis   
    image: redis:latest

  seq:
    container_name: seq
    image: datalust/seq:latest

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-04-28T17-53-50Z.fips

  book.api:
    container_name: book.api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: . 
      dockerfile: ../Services/Book/Api/Dockerfile
    depends_on: [minio, redis, mssql]
    
  monitoring.api:
    container_name: monitoring.api
    image: ${DOCKER_REGISTRY-}monitoringapi
    build:
      context: .
      dockerfile: ../Services/Monitoring/Monitoring.Api/Dockerfile
    depends_on: [book.api]